Models/CessionModel.cs
using System;

namespace SitePeche.Models
{
    public class CessionModel
    {
        public int id{get; set;}
        public string meteo{get;set;}
        public string maree{get;set;}
        public string date{get;set;}
        public int site_id{get;set;}
        public string site_nom{set;get;}

        public CessionModel(int id, string meteo, string maree, string date,
        int site_id, string site_nom)
        {
            this.id = id;
            this.meteo = meteo;
            this.maree = maree;
            this.date = date;
            this.site_id = site_id;
            this.site_nom = site_nom;
        }
    }
}

Models/ErrorViewModel.cs
using System;

namespace SitePeche.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/EspeceModel.cs
namespace SitePeche.Models
{
    public class EspeceModel
    {
        public int id {get; set;}
        public string nom {get; set;}
        public string nom_alt {get; set;}
        public int taille_min {get; set;}

        public EspeceModel(int id, string nom, string nom_alt, int taille_min)
        {
            this.id = id;
            this.nom = nom;
            this.nom_alt = nom_alt;
            this.taille_min = taille_min;
        }
    }
}

Models/PriseModel.cs
using System;

namespace SitePeche.Models
{
    public class PriseModel
    {
        public int id {get;set;}
        public int taille {get; set;}
        public bool preleve {get; set;}
        public int id_cession {get; set;}
        public int id_espece {get; set;}
        public string nom_espece {get; set;}
        public string nom_alt_espece {get;set;}
        public int id_spot {set; get;}
        public string nom_spot {get;set;}
        public string gps_spot {get;set;}
        public PriseModel(int id, int taille, bool preleve, int id_cession, int id_espece,
        string nom_espece, string nom_alt_espece, int id_spot, string nom_spot, string gps_spot)
        {
            this.id = id;
            this.taille = taille;
            this.preleve = preleve;
            this.id_cession = id_cession;
            this.id_espece = id_espece;
            this.nom_espece = nom_espece;
            this.nom_alt_espece = nom_alt_espece;
            this.id_spot = id_spot;
            this.nom_spot = nom_spot;
            this.gps_spot = gps_spot;
        }
    }
}

Models/SiteModel.cs
using System;

namespace SitePeche.Models
{
    public class SiteModel
    {
        public int id {get;set;}
        public string nom {get;set;}

        public SiteModel(int id, string nom)
        {
            this.id = id;
            this.nom = nom;
        }
    }
}

Models/SpotModel.cs
using System;

namespace SitePeche.Models
{
    public class SpotModel
    {
        public int id {get;set;}
        public string nom {get;set;}
        public string gps {get; set;}
        public int id_site {get;set;}

        public SpotModel(int id, string nom, string gps, int id_site)
        {
            this.id = id;
            this.nom = nom;
            this.gps = gps;
            this.id_site = id_site;
        }
    }
}

Controllers/CessionController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using SitePeche.Services;

namespace SitePeche.Controllers
{
    public class CessionController : Controller
    {
        public IActionResult Index()
        {
            return View(DbCessionGetAll.Instance().CessionGetAll());
        }

        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Detail(int id)
        {
            ViewBag.prise = DbPriseGetAll.Instance().PriseGetAll(id);
            return View(DbCessionGetOne.Instance().CessionGetOne(id));
        }
    }
}

Controllers/EspeceController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using SitePeche.Services;
using SitePeche.Models;

namespace SitePeche.Controllers
{
    public class EspeceController : Controller
    {
        public IActionResult Index()
        {
            return View(DbEspeceGetAll.Instance().EspeceGetAll());
        }
        // GET: Espece/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(string nom, string nom_alt, int taille_min)
        {
            DbEspeceCreate.Instance().EspeceCreate(nom, nom_alt, taille_min);
            return RedirectToAction("Index");
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SitePeche.Models;

namespace SitePeche.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/SiteController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using SitePeche.Services;

namespace SitePeche.Controllers
{
    public class SiteController : Controller
    {
        public IActionResult Index()
        {
            return View(DbSiteGetAll.Instance().SiteGetAll());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(string nom)
        {
            DbSiteCreate.Instance().SiteCreate(nom);
            return RedirectToAction("Index");
        }

        public IActionResult Detail(int id)
        {
            ViewBag.spot = DbSpotGetAll.Instance().SpotGetAll(id);
            return View(DbSiteGetOne.Instance().SiteGetOne(id));
        }
    }
}

Controllers/SpotController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using SitePeche.Services;

namespace SitePeche.Controllers
{
    public class SpotController : Controller
    {
        public IActionResult Create(int id)
        {
            ViewBag.SiteId = id;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(string nom, string gps, int id_site)
        {
            DbSpotCreate.Instance().SpotCreate(nom, gps, id_site);
            return RedirectToAction("Index");
        }
    }
}

Views/Cession/Create.cshtml
@{
    ViewData["Title"] = "Ajouter une nouvelle cession";
}
<h2>@ViewData["Title"]</h2>

Views/Cession/Detail.cshtml
@{
    ViewData["Title"] = "Détail de la cession";
}
<h2>@ViewData["Title"]</h2>
<ul>
    <li><strong>Info Météo: </strong>@Model.meteo</li>
    <li><strong>Info marée: </strong>@Model.maree</li>
    <li><strong>Nom du site: </strong>@Model.site_nom</li>
</ul>

<h3>Prises de la cession</h3>
<a>
    @Html.ActionLink("Ajouter une nouvelle prise","Create","Prise")
</a>
<table class ="table table-striped">
    <tr>
        <td>Espece</td>
        <td>Taille</td>
        <td>Prelèvement</td>
        <td>Spot</td>
        <td>Coordonnées GPS</td>
    </tr>
    @foreach (var item in ViewBag.prise)
    {
    <tr>
        <td>@item.nom_espece</td>
        <td>@item.taille</td>
        <td>@item.preleve</td>
        <td>@item.nom_spot</td>
        <td>@item.gps_spot</td>
    </tr>
    }
</table>

Views/Cession/Index.cshtml
@{
    ViewData["Title"] = "Mes cessions de pêche";
}
    <a>
        @Html.ActionLink("Ajouter une nouvelle cession","Create","Cession")
    </a>
<table class="table table-striped">
    <tr>
        <th>ID</th>
        <th>Date</th>
        <th>Site</th>
        <th>Marée</th>
        <th>Météo</th>
        <th>Action</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.id</td>
            <td>@item.date</td>
            <td>@item.site_nom</td>
            <td>@item.maree</td>
            <td>@item.meteo</td>
            <td>
                <a>
                    @Html.ActionLink("Consulter","Detail",new {id = item.id})
                </a>
            </td>
        </tr>
    }
</table>

Views/Espece/Create.cshtml
@model EspeceModel
@{
    ViewData["Title"] = "Ajouter une nouvelle espèce";
}
<h2>@ViewData["Title"]</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>espèce</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nom_alt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom_alt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nom_alt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.taille_min, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.taille_min, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.taille_min, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Espece/Index.cshtml
@{
    ViewData["Title"] = "Espèces de poisson";
}
<h2>@ViewData["Title"]</h2>
<a>
    @Html.ActionLink("Ajouter une nouvelle espèce","Create")
</a>
<table class="table table-striped">
    <tr>
        <th>Nom</th>
        <th>Nom alternatif</th>
        <th>Taille minimum de prélèvement</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.nom</td>
            <td>@item.nom_alt</td>
            <td>@item.taille_min</td>
        </tr>
    }
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/vazen.jpg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p></p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/vieille.jpg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p></p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/sars.jpg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p></p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SitePeche</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">SitePeche</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Cession" asp-action="Index">Cession</a></li>
                    <li><a asp-area="" asp-controller="Site" asp-action="Index">Site</a></li>
                    <li><a asp-area="" asp-controller="Espece" asp-action="Index">Espèce</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - SitePeche</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Site/Create.cshtml
@model SiteModel
@{
    ViewData["Title"] = "Ajouter un nouveau site";
}
<h2>@ViewData["Title"]</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Site</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nom, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Site/Detail.cshtml
@{
    ViewData["Title"] = "Détail du site";
}
<h2>@ViewData["Title"]</h2>


<h3>Site de @Model.nom </h3>
<a>
    @Html.ActionLink("Ajouter un nouveau spot","Create","Spot",new{id = Model.id})
</a>

<table class ="table table-striped">
    <tr>
        <td>Nom du spot</td>
        <td>Coordonnées GPS</td>
    </tr>
    @foreach (var item in ViewBag.spot)
    {
    <tr>
        <td>@item.nom</td>
        <td>@item.gps</td>
    </tr>
    }
</table>

Views/Site/Index.cshtml
@{
    ViewData["Title"] = "Mes sites de pêche";
}
<h2>@ViewData["Title"]</h2>

<a>
    @Html.ActionLink("Ajout d'un nouveau site","Create","Site")
</a>

<table class="table table-striped">
    <tr>
        <th>Nom du site</th>
        <th>Action</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.nom</td>
            <td>                 
                <a>
                    @Html.ActionLink("Consulter","Detail",new {id = item.id})
                </a>
            </td>
        </tr>
    }

</table>

Views/Spot/Create.cshtml
@model SpotModel
@{
    ViewData["Title"] = "Ajouter un nouveau spot";
}
<h2>@ViewData["Title"]</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>espèce</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.gps, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.gps, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.gps, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_site, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id_site, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id_site, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index","Site")
</div>